name: Semgrep

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  semgrep:
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - uses: actions/checkout@v6

      - name: Run Semgrep
        run: semgrep scan --config auto